// Appendix 2 "Injection sites for BoNT-A" uit
// Spasticity in adults: management using botulinum toxin,
// Royal College of Physicians, 2e editie 2018, bladzijde 53-63.
//
// Eén bestand, want twee pagina's gebruiken deze cijfers: rcp-spieren.html
// toont ze en dosering.html leest er het aantal injectieplaatsen en het
// volwassenbereik uit. Klinische getallen horen op één plek te staan.
//
// LET OP: dit zijn doses voor VOLWASSENEN. De richtlijn geeft geen
// kinderdosis, geen dosis per kilogram en geen plafond per sessie.

(function (global) {
  'use strict';

  // ------------------------------------------------------------------
  // Appendix 2 "Injection sites for BoNT-A" — Spasticity in adults:
  // management using botulinum toxin, Royal College of Physicians,
  // 2nd edition 2018, p. 53-63.
  //
  // Overgetypt van de foto's van de bron, uitvergroot per rij nagelezen.
  // b = BOTOX, d = Dysport, x = Xeomin; [min, max] of [waarde] bij een
  // enkel getal; null waar de tabel geen dosis geeft.
  // n  = aantal injectieplaatsen ALLEEN als de bron het zelf noemt.
  // sic = afwijking in de bron die ik niet stilzwijgend heb gecorrigeerd.
  // ------------------------------------------------------------------
  var GROEPEN = [
    { id: 'romp',    nl: 'Rompspieren',                              en: 'Trunk muscles' },
    { id: 'heup',    nl: 'Heupextensoren en -abductoren',            en: 'Hip extensors and abductors' },
    { id: 'knie',    nl: 'Bovenbeen — knie-extensoren',              en: 'Thigh – knee extensors' },
    { id: 'add',     nl: 'Bovenbeen — adductoren en knieflexoren',   en: 'Thigh adductors and knee flexors' },
    { id: 'onderAL', nl: 'Onderbeen — anterolateraal',               en: 'Lower leg – antero lateral compartment' },
    { id: 'onderP',  nl: 'Onderbeen — posterieur (en voetspieren)',  en: 'Lower leg – posterior compartment' },
    { id: 'gordel',  nl: 'Schoudergordel',                           en: 'Pectoral girdle' },
    { id: 'arm',     nl: 'Arm',                                      en: 'Arm' },
    { id: 'armExt',  nl: 'Onderarm — strekzijde',                    en: 'Extensor aspect of forearm' },
    { id: 'armFlex', nl: 'Onderarm — buigzijde',                     en: 'Flexor aspect of forearm' }
  ];

  var RCP = [
    // --- Trunk muscles (p. 53) ---
    { g: 'romp', m: 'Psoas major', a: 'Flexes hip',
      b: [100, 200], d: [600, 800], x: [100, 200],
      p: 'Approach posteriorly advancing spinal needle between transverse processes at L2, L3 and L4. 50–60U at each site',
      n: '3 plaatsen — L2, L3 en L4, 50–60U per plaats' },
    { g: 'romp', m: 'Iliacus', a: 'Flexes hip',
      b: [75, 150], d: [200, 400], x: [75, 150],
      p: 'Anterior approach under lateral third of inguinal ligament – lateral to femoral nerve and avoiding lateral cutaneous nerve of thigh' },
    { g: 'romp', m: 'Quadratus lumborum', a: 'Flexes vertebral column laterally',
      b: [100], d: [400], x: [100],
      p: 'Posterior approach lateral to vertebral column' },

    // --- Hip extensors and abductors (p. 53-54) ---
    { g: 'heup', m: 'Gluteus maximus', a: 'Extends thigh. Laterally rotates hip', zelden: true, p: '' },
    { g: 'heup', m: 'Gluteus medius', a: 'Abducts leg', b: [100], d: [400], x: [100], p: '' },
    { g: 'heup', m: 'Gluteus minimus', a: 'Abducts leg', zelden: true, p: '' },

    // --- Thigh – knee extensors (p. 54) ---
    { g: 'knie', m: 'Rectus femoris', a: 'Hip flexion and knee extension',
      b: [100, 150], d: [400, 500], x: [100, 150],
      p: 'Four points along the middle of quadriceps muscle mass',
      n: '4 plaatsen' },
    { g: 'knie', m: 'Vastus lateralis, intermedius and medialis', a: 'Knee extension',
      b: [100, 150], d: [400, 500], x: [100, 150],
      p: 'Two points in lateral aspect of thigh; one deep centrally in lower half of thigh and one to two medially',
      n: 'meerdere plaatsen — twee lateraal, één diep centraal, één à twee mediaal' },

    // --- Thigh adductors and knee flexors (p. 54-55) ---
    { g: 'add', m: 'Pectineus', a: 'Adducts thigh and assists hip flexion',
      b: [50, 100], d: [200, 400], x: [50, 100],
      p: 'Difficult to inject because of overlying neurovascular bundle below inguinal ligament medial to femoral vein' },
    { g: 'add', m: 'Adductor magnus', a: 'Adducts and laterally. Main action while sitting',
      b: [100, 200], d: [400, 750], x: [100, 200],
      dosisNoot: 'De tabel zet er bij de BOTOX-dosis uitdrukkelijk „into whole adductor group" bij — het is een dosis voor de hele adductorengroep, niet voor deze ene spier.',
      p: 'Large muscle in upper medial thigh. Inject into upper third of thigh' },
    { g: 'add', m: 'Adductor longus', a: 'Adducts thigh. Main action on standing',
      b: null, d: null, x: null,
      geenDosis: 'De tabel laat de dosiscel hier leeg; de dosis staat bij adductor magnus, voor de hele adductorengroep.',
      p: "Antero medial aspect of thigh one hand's breadth below inguinal ligament medial to femoral vein" },
    { g: 'add', m: 'Adductor brevis', a: 'Adducts and laterally rotates thigh', zelden: true,
      p: 'Behind adductor longus and pectineus and in front of adductor magnus' },
    { g: 'add', m: 'Gracilis', a: 'Adducts thigh and flexes knee. Medially rotates flexed leg',
      b: [80, 120], d: [300, 400], x: [80, 120],
      p: 'Postero medial edge of thigh several points of injection down medial thigh',
      n: 'meerdere plaatsen — „several points … down medial thigh"' },
    { g: 'add', m: 'Semi membranosus', a: 'Flexes knee. Medially rotates flexed leg and extends hip',
      b: [100, 150], d: [400, 500], x: [100, 150],
      p: 'Medial muscles in posterior thigh – multiple injection sites',
      n: 'meerdere plaatsen' },
    { g: 'add', m: 'Semi tendinosus', a: 'Same as semi membranosus',
      b: [100, 150], d: [400, 600], x: [100, 150],
      p: 'Medial muscles in posterior thigh – multiple injection sites',
      n: 'meerdere plaatsen' },
    { g: 'add', m: 'Biceps femoris', a: 'Flexes knee, rotates leg externally and extends hip',
      b: [100, 150], d: [400, 600], x: [100, 150],
      p: 'Lateral muscle in posterior thigh – multiple injection sites',
      n: 'meerdere plaatsen' },
    { g: 'add', m: 'Popliteus', a: 'Flexes knee and internally rotates lower leg at beginning of flexion',
      b: [25, 30], d: [100, 120], x: [25, 30],
      p: 'Deep over back of medial tibial condyle. Down to bone medial aspect of popliteal fossa and then withdraw' },

    // --- Lower leg – antero lateral compartment (p. 56) ---
    { g: 'onderAL', m: 'Tibialis anterior', a: 'Dorsiflexes and inverts foot',
      b: [75, 120], d: [300, 400], x: [75, 120],
      p: 'Front of shin, lateral to tibia' },
    { g: 'onderAL', m: 'Extensor digitorum longus', a: 'Dorsiflexes foot and toes 2–5',
      b: [50, 75], d: [200, 300], x: [50, 80],
      p: 'Lateral to tibialis anterior in front of and border of fibula' },
    { g: 'onderAL', m: 'Extensor hallucis longus', a: 'Extends great toe',
      b: [50, 60], d: [200, 250], x: [50, 60],
      p: 'Between tibialis anterior and extensor digitorum longus in middle of shin' },
    { g: 'onderAL', m: 'Peroneus tertius (not always present)', a: 'Dorsi flexes and everts foot',
      b: [30, 40], d: [120, 150], x: [30, 40],
      p: 'Attached to ext digitorum longus lateral surface' },
    { g: 'onderAL', m: 'Peroneus longus', a: 'Everts and plantar flexes foot',
      b: [50, 80], d: [200, 320], x: [50, 80],
      p: 'Lateral aspect of shin anterior to fibula' },
    { g: 'onderAL', m: 'Peroneus brevis', a: 'Everts foot',
      b: [30, 40], d: [120, 160], x: [30, 40],
      p: 'Lower half of lateral shin anterior to peroneus longus' },

    // --- Lower leg – posterior compartment (p. 57-58) ---
    { g: 'onderP', m: 'Gastrocnemius – medial head', a: 'Plantar flexes foot and flexes knee',
      b: [50, 100], d: [200, 400], x: [50, 100],
      p: 'Superficial muscle of medial aspect of calf' },
    { g: 'onderP', m: 'Gastrocnemius – lateral head', a: 'Plantar flexes foot and flexes knee',
      b: [50, 100], d: [200, 400], x: [50, 100],
      p: 'Superficial muscle of lateral aspect of calf' },
    { g: 'onderP', m: 'Soleus', a: 'Plantar flexes foot',
      b: [75, 100], d: [300, 400], x: [75, 200],
      p: 'Back of calf, midway down between muscle bellies of gastrocnemius' },
    { g: 'onderP', m: 'Flexor hallucis longus', a: 'Flexes great toe (IP + MTP joints) maintains longitudinal arch',
      b: [40, 60], d: [160, 240], x: [40, 60],
      p: 'Under soleus mid-calf immediately posterior to peroneus longus and fibula' },
    { g: 'onderP', m: 'Flexor digitorum longus', a: 'Flexes toes 2–5 (IP + MTP joints) and maintains longitudinal arch',
      b: [40, 60], d: [160, 200], x: [40, 60],
      p: 'Behind medial border of tibia in its upper mid area. Inject near origin just behind tibia' },
    { g: 'onderP', m: 'Tibialis posterior', a: 'Plantar flexes and inverts foot',
      b: [50, 80], d: [200, 320], x: [50, 80],
      p: 'Mid-calf, deep behind tibia and in depression between tibia and fibula' },
    { g: 'onderP', m: 'Abductor hallucis', a: 'Abducts and plantar flexes great toe',
      b: [10, 20], d: [40, 80], x: [10, 20],
      p: 'Medial aspect 1st metatarsal' },
    { g: 'onderP', m: 'Flexor hallucis brevis', a: 'Flexes 1st MTP joint',
      b: [10, 20], d: [40, 80], x: [10, 20],
      p: 'Plantar aspect of foot under 1st metatarsal' },
    { g: 'onderP', m: 'Flexor digitorum brevis', a: 'Flexes 1st IP joint and lateral four MTP joints',
      b: [10, 20], d: [40, 80], x: [10, 20],
      p: 'Plantar aspect of foot at base of metatarsals' },

    // --- Pectoral girdle (p. 58-60) ---
    { g: 'gordel', m: 'Trapezius', a: 'Scapular elevation and rotation',
      b: [50, 75], d: [200, 300], x: [50, 75],
      p: 'Large muscle between neck and shoulder' },
    { g: 'gordel', m: 'Rhomboid', a: 'Extension of scapulae',
      b: [50, 60], d: [200, 250], x: [50, 60],
      p: 'Superficial, between scapula and spine' },
    { g: 'gordel', m: 'Supraspinatus', a: 'Abd. of arm from 0–15° above 90°',
      b: [40, 50], d: [160, 200], x: [40, 50],
      p: 'Supraspinous fossa on scapula' },
    { g: 'gordel', m: 'Infraspinatus', a: 'External rotation of arm',
      b: [50, 60], d: [200, 240], x: [50, 60],
      p: 'Infraspinous surface of scapula' },
    { g: 'gordel', m: 'Subscapularis', a: 'Internal rotation of arm',
      b: [50, 80], d: [200, 320], x: [15, 100],
      p: 'Inject under lateral border of scapula' },
    { g: 'gordel', m: 'Deltoid', a: 'Arm adduct from 15–90°',
      b: [50, 75], d: [200, 300], x: [20, 150],
      p: 'Inject anterior, middle and posterior fibres',
      n: '3 plaatsen — voorste, middelste en achterste vezels' },
    { g: 'gordel', m: 'Teres major', a: 'Adducts, medially rotates and extends arm',
      b: [30, 50], d: [120, 200], x: [20, 100],
      p: 'Lateral aspect lower scapula' },
    { g: 'gordel', m: 'Teres minor', a: 'Adducts and laterally rotates',
      b: [30, 50], d: [120, 200], x: [30, 50],
      p: 'Lateral aspect scapula above' },
    { g: 'gordel', m: 'Latissimus dorsi', a: 'Adducts, retracts and medially rotates upper limb',
      b: [60, 80], d: [240, 320], x: [25, 150],
      p: 'Find in posterior fold of axilla while asking patient to pull down elevated arm' },
    { g: 'gordel', m: 'Serratus anterior', a: 'Protracts upper limb',
      b: [60, 70], d: [250, 275], x: [60, 70],
      p: 'Lateral aspect of upper eight ribs' },
    { g: 'gordel', m: 'Pectoralis major', a: 'Adducts and medially rotates',
      b: [75, 100], d: [300, 400], x: [20, 200],
      p: 'Anterior axillary fold' },
    { g: 'gordel', m: 'Pectoralis minor', a: 'Draw scapula down and forwards, depresses shoulder',
      b: [40], d: [160], x: [40],
      p: 'Deep to upper part of pectoralis major' },

    // --- Arm (p. 60) ---
    { g: 'arm', m: 'Biceps brachii', a: 'Supination and elbow flexion',
      b: [75, 100], d: [100, 300], x: [75, 100],
      p: 'Anterior aspect of upper arm. Inject both heads',
      n: '2 plaatsen — beide koppen' },
    { g: 'arm', m: 'Triceps brachii', a: 'Elbow extension',
      b: [75, 100], d: [300, 400], x: [75, 100],
      p: 'Three heads on post aspect of arm',
      n: '3 koppen aan de achterzijde' },
    { g: 'arm', m: 'Coracobrachialis', a: 'Flexes and adducts upper arm',
      b: [30, 50], d: [120, 200], x: [30, 50],
      p: 'Medial to upper humerus between it and neurovascular bundle' },
    { g: 'arm', m: 'Brachialis', a: 'Flexes elbow',
      b: [50, 75], d: [200, 400], x: [50, 75],
      p: 'Lower anterior humerus medial and lateral of biceps tendon' },

    // --- Extensor aspect of forearm (p. 60-62) ---
    { g: 'armExt', m: 'Brachioradialis', a: 'Elbow flexion',
      b: [50, 60], d: [200, 240], x: [50, 60],
      p: 'Radial side upper forearm' },
    { g: 'armExt', m: 'Supinator', a: 'Supinates forearm',
      b: [30, 40], d: [120, 160], x: [30, 40],
      p: 'Extensor aspect of arm below radial neck – deep' },
    { g: 'armExt', m: 'Extensor carpi radialis longus', a: 'Extends and adducts hand at wrist',
      b: [30, 40], d: [120, 160], x: [30, 40],
      p: 'Posterior to brachio-radialis on back of forearm' },
    { g: 'armExt', m: 'Extensor carpi radialis brevis', a: 'Extends and adducts hand at wrist',
      b: [20, 30], d: [75, 120], x: [20, 30],
      p: 'Posterior and medial to ECR longus' },
    { g: 'armExt', m: 'Extensor carpi ulnaris', a: 'Extends wrist and elbow and adducts hand',
      b: [30, 40], d: [120, 160], x: [30, 40],
      p: 'Most medially placed extensor muscle. Halfway down ulna shaft' },
    { g: 'armExt', m: 'Extensor digitorum communis', a: 'Extends wrist and fingers',
      b: [30, 40], d: [120, 160], x: [30, 40],
      p: 'Middle of back of forearm distal to radial tuberosity' },
    { g: 'armExt', m: 'Extensor digiti minimi', a: 'Extends 5th finger',
      b: [30, 40], d: [120, 160], x: [30, 40],
      p: 'Medial to ext digitorum' },
    { g: 'armExt', m: 'Extensor pollicis longus', a: 'Extends all joints of thumb',
      b: [20, 30], d: [75, 120], x: [20, 30],
      p: 'Midway down back of forearm' },
    { g: 'armExt', m: 'Extensor pollicis brevis', a: 'Extends CMC and MCP joints of thumb',
      b: [20, 25], d: [75, 100], x: [20, 25],
      p: 'Distal third of forearm. Palpate by moving CMC and MCP joints' },
    { g: 'armExt', m: 'Adductor pollicis longus', a: 'Adducts thumb and hand',
      b: [20, 40], d: [80, 120], x: [20, 40],
      p: 'Proximal to ext pollicis brevis on back of forearm. Palpate action',
      sic: 'De tabel drukt „Adductor pollicis longus" af. Uit de insertie (base of 1st MC) en de ligging op de strekzijde blijkt dat de <b>abductor</b> pollicis longus bedoeld is. Ik heb de naam laten staan zoals de bron hem geeft.' },
    { g: 'armExt', m: 'Extensor indicis', a: 'Extends forefinger',
      b: [20, 30], d: [75, 120], x: [20, 30],
      p: 'Found medial of most lateral tendon of ext digit communis' },

    // --- Flexor aspect of forearm (p. 62-63) ---
    { g: 'armFlex', m: 'Pronator teres', a: 'Pronates forearm and flexes elbow',
      b: [30, 40], d: [120, 160], x: [30, 40],
      p: 'Medial border of anterior cubital fossa – medial to brachial artery',
      sic: 'In de tabel staat boven deze rij, in dezelfde cel, het kopje „Superficial flexor muscles".' },
    { g: 'armFlex', m: 'Flexor carpi radialis', a: 'Flexes wrist and elbow',
      b: [30, 40], d: [120, 160], x: [30, 40],
      p: 'Upper forearm just below bicipital aponeurosis and medial to pronator teres' },
    { g: 'armFlex', m: 'Flexor carpi ulnaris', a: 'Flexes and adducts hand at wrist',
      b: [30, 40], d: [120, 160], x: [30, 40],
      p: 'Upper forearm medial aspect of flexor surface below bicipital aponeurosis. Medial to FCR. Observe action of wrist flexion' },
    { g: 'armFlex', m: 'Flexor digitorum superficialis', a: 'PIP joint flexor and MCP joint flexor',
      b: [25, 30], d: [100, 120], x: [25, 30],
      p: 'Middle of forearm half way down to either side of palmaris tendon',
      n: '2 plaatsen — weerszijden van de pees van de palmaris' },
    { g: 'armFlex', m: 'Flexor digitorum profoundus', a: 'Flexes all finger joints',
      b: [30, 40], d: [120, 160], x: [30, 40],
      p: 'Upper third of forearm. Deep muscle above lateral border of ulna',
      sic: 'De bron spelt „profoundus"; gangbaar is <em>profundus</em>.' },
    { g: 'armFlex', m: 'Flexor pollicis longus', a: 'Flexes all joints of thumb',
      b: [20, 30], d: [75, 120], x: [20, 30],
      p: 'Mid forearm over anterior aspect of radius' },
    { g: 'armFlex', m: 'Pronator quadratus', a: 'Pronates forearm',
      b: [20, 30], d: [75, 120], x: [20, 30],
      p: 'Approach muscle from extensor aspect of forearm just proximal to wrist and advance through interosseous membrane' }
  ];
  global.RCP_APPENDIX2 = { groepen: GROEPEN, spieren: RCP };
})(typeof window !== 'undefined' ? window : this);
